openapi: 3.0.3
info:
  title: Transaction - OpenAPI 3.0
  description: |-
    Transaction API Spec
  version: 1.0.0
servers:
  - url: api/v1
paths:
  /purchase:
    post:
      tags:
        - transaction
      summary: Add a new transaction
      description: Add a new transaction
      operationId: addTransaction
      requestBody:
        description: Create a new purchase transaction
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error


components:
  schemas:
    Transaction:
      type: object
      properties:
        identifier:
          type: integer
        description:
          type: string
          maxLength: 50
          example: John
        transactionDate:
          type: string
          format: date
        amount:
          type: number
          format: double
        converted_amount:
          type: number
          format: double
        exchange_rate:
          type: number
          format: double

        required: # Correct
          - identifier
          - description
          - transactionDate
          - amount
